project:
  type: website
  preview:
    port: 4200
    browser: false

metadata-files:
  - _data/cv.yml

execute:
  freeze: true

website:
  site-url: https://aleixalcacer.com
  description: "Personal website of Aleix Alcacer - Postdoctoral researcher"
  title: "Aleix Alcacer"
  navbar:
    background: light
    title: "Aleix Alcacer"
    left:
      - href: index.qmd
        text: About
      - href: cv/index.qmd
        text: CV
      - href: research/index.qmd
        text: Research
      - href: teaching/index.qmd
        text: Teaching        
      - href: os-projects/index.qmd
        text: OS Projects
      # - href: skills/index.qmd
      #   text: Skills
      - href: posts/index.qmd
        text: Blog
    right:
      - icon: rss-fill
        href: posts/index.xml
      
  page-footer:
    center: Made with {{< fa heart >}} using Quarto
    background: light
    border: false

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    css: styles.css
